version: '3'

services:
  videosite-front:
    build: ./front
    container_name: videosite-front-dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports: 
      - "3003:3003"
    command: npm run dev

  videosite-backend:
    build: ./backend
    container_name: videosite-backend-dev
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports: 
      - "3004:3003"
    command: npm run watch

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: 123
