# ohjeita: https://circleci.com/blog/build-cicd-piplines-using-docker/

version: 2
jobs:
    build:
        machine: true
        working_directory: ~/front
        steps:
            - checkout
            # start proprietary DB using private Docker image
            # with credentials stored in the UI
            - run: |
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                # docker run -d --name db company/proprietary-db:1.2.3

            # build the application image
            - run: docker build -t lasa/videosite:$CIRCLE_BRANCH .

            # deploy the image
            - run: docker push lasa/videosite:$CIRCLE_BRANCH
            
            - run:
                name: oubs-nasu
                command: ssh -o "StrictHostKeyChecking no" oubsadmin@nasu.oubs.fi "touch testifile"
 #           - run:
 #               name: docker-pull
 #               command: ssh -o "StrictHostKeyChecking no" oubsadmin@nasu.oubs.fi "docker pull lasa/videosite; docker restart lasa/videosite"

