# ohjeita: https://circleci.com/blog/build-cicd-piplines-using-docker/

version: 2
jobs:
    build:
        docker:
            - image: circleci/node:8.11.2
        working_directory: ~/front
        steps:
            - checkout
            # start proprietary DB using private Docker image
            # with credentials stored in the UI
            - setup_remote_docker
            #- run:
            #    name: Install Docker client
            #    command: |
            #        set -x
            #        VER="17.03.0-ce"
            #        curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            #        tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            #        mv /tmp/docker/* /usr/bin

            # build the application image
            - run: |
                TAG=0.1.$CIRCLE_BUILD_NUM
                docker build -t lasa/videosite:$TAG .
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker push lasa/videosite:$TAG
                # docker run -d --name db company/proprietary-db:1.2.3

            #- run:
            #    name: oubs-nasu
            #    command: ssh -o "StrictHostKeyChecking no" oubsadmin@nasu.oubs.fi "touch testifile"
            - run:
                name: docker-start
                command: ssh -o "StrictHostKeyChecking no" oubsadmin@nasu.oubs.fi "cd ~/dockerfiles/docker-videosite; docker-compose up -d"

